#:kivy 2.3.1
<MotorScreen>:
    # Main cylinder page
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 10
        
        # bore box
        GridLayout:
            cols: 2
            padding: 10
            spacing: 10
            TextInput:
                id: displacement_input
                hint_text: "Displacement (in³)"
                font_size: '40sp'
                size_hint_x: None
                width: root.width * 0.75
                halign: 'center'
                valign: 'middle'
                padding_y: [self.height / 2 - self.line_height /2]
            BoxLayout:
                padding: 10
                spacing: 10
                orientation: "vertical"
                MotorAdjustButton:
                    text: "+ 0.5"
                    #key: "displacement"
                    amount: 0.5
                    #screen: root

                MotorAdjustButton:
                    text: "-0.5"
                    #key: "displacement"
                    amount: -0.5
                    #screen: root

        
        # rod box
        GridLayout:
            cols: 2
            padding: 10
            spacing: 10
            TextInput:
                id:  flow_input
                hint_text: "Flow (gpm)"
                font_size: '40sp'
                size_hint_x: None
                width: root.width * 0.75
                halign: 'center'
                valign: 'middle'
                padding_y: [self.height / 2 - self.line_height /2]
            BoxLayout:
                padding: 10
                spacing: 10
                orientation: "vertical"
                MotorAdjustButton:
                    text: "+.25"
                    #key: "flow"
                    amount: 0.25
                    #screen: root
                MotorAdjustButton:
                    text: "-.25"
                    #key: "flow"
                    amount: -0.25
                    #screen: root

        
        #presssure box
        GridLayout:
            cols: 2
            padding: 10
            TextInput:
                id: pressure_input
                hint_text: "Pressure (psi)"
                font_size: '40sp'
                size_hint_x: None
                width: root.width * 0.75
                halign: 'center'
                valign: 'middle'
                padding_y: [self.height / 2 - self.line_height /2]
            BoxLayout:
                orientation: "vertical"
                padding: 10
                spacing: 10
                MotorAdjustButton:
                    text: "+100"
                    #key: "pressure"
                    amount: 100
                    #screen: root

                MotorAdjustButton:
                    text: "-100"
                    #key: "pressure"
                    amount: -100
                    #screen: root

        
        # output box
        Label:
            id: output_label
            text: "Motor torque: 0 \nMotor speed: 0 "

        
        # Bottom buttons box
        GridLayout:
            rows: 1
            Button:
                text: "Calculate"
                on_press: #root.calculate()
            Button:
                text: "Reset"
                on_press: root.reset()
            Button:
                text: "Back"
                on_press: root.go_back()
            Button:
                text: "save"
