#:kivy 2.3.1

<PumpScreen>:
    # Main cylinder page
    BoxLayout:
        orientation: "vertical"
        spacing: 5
        padding: 5

        # label above displacement box
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            height: 20
            Label:
                text: "Displacement"
                halign: 'left'
                valign: 'middle'
                text_size: self.size
        
        # displacement box
        GridLayout:
            cols: 2
            padding: 10
            spacing: 10
            TextInput:
                id: displacement_input
                hint_text: "Displacement (in³)"
                font_size: '40sp'
                size_hint_x: None
                width: root.width * 0.75
                halign: 'center'
                valign: 'middle'
                padding_y: [self.height / 2 - self.line_height /2]
            BoxLayout:
                padding: 10
                spacing: 10
                orientation: "vertical"
                PumpAdjustButton:
                    text: "+ 0.5"
                    key: "displacement"
                    amount: 0.5
                    screen: root

                PumpAdjustButton:
                    text: "-0.5"
                    key: "displacement"
                    amount: -0.5
                    screen: root

        # label above rpm box
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            height: 20
            Label:
                text: "RPM"
                halign: 'left'
                valign: 'middle'
                text_size: self.size

        
        # rpm box
        GridLayout:
            cols: 2
            padding: 10
            spacing: 10
            TextInput:
                id:  rpm_input
                hint_text: "Speed (rpm)"
                font_size: '40sp'
                size_hint_x: None
                width: root.width * 0.75
                halign: 'center'
                valign: 'middle'
                padding_y: [self.height / 2 - self.line_height /2]
            BoxLayout:
                padding: 10
                spacing: 10
                orientation: "vertical"
                PumpAdjustButton:
                    text: "+.25"
                    key: "rpm"
                    amount: 0.25
                    screen: root
                PumpAdjustButton:
                    text: "-.25"
                    key: "rpm"
                    amount: -0.25
                    screen: root

        # label above the pressure box box
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            height: 20
            Label:
                text: "Pressure"
                halign: 'left'
                valign: 'middle'
                text_size: self.size

        #presssure box
        GridLayout:
            cols: 2
            padding: 10
            TextInput:
                id: pressure_input
                hint_text: "Pressure (psi)"
                font_size: '40sp'
                size_hint_x: None
                width: root.width * 0.75
                halign: 'center'
                valign: 'middle'
                padding_y: [self.height / 2 - self.line_height /2]
            BoxLayout:
                orientation: "vertical"
                padding: 10
                spacing: 10
                PumpAdjustButton:
                    text: "+100"
                    key: "pressure"
                    amount: 100
                    screen: root

                PumpAdjustButton:
                    text: "-100"
                    key: "pressure"
                    amount: -100
                    screen: root

        
        # output box
        Label:
            id: output_label
            text: "Pump output flow: 0 \nHorsepower: 0 "

        
        # Bottom buttons box
        GridLayout:
            rows: 1
            Button:
                text: "Calculate"
                on_press: root.calculate()
            Button:
                text: "Reset"
                on_press: root.reset()
            Button:
                text: "Back"
                on_press: root.go_back()
            Button:
                text: "save"
  
    